2021-11-10 13:43:54,564 INFO    MainThread:33598 [wandb_setup.py:_flush():71] setting env: {}
2021-11-10 13:43:54,564 INFO    MainThread:33598 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-10 13:43:54,564 INFO    MainThread:33598 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-10 13:43:54,564 INFO    MainThread:33598 [wandb_init.py:_log_setup():357] Logging user logs to /opt/ml/alchera-ai-challenge/baseline/torch_dev/wandb/run-20211110_134354-1l1npq21/logs/debug.log
2021-11-10 13:43:54,564 INFO    MainThread:33598 [wandb_init.py:_log_setup():358] Logging internal logs to /opt/ml/alchera-ai-challenge/baseline/torch_dev/wandb/run-20211110_134354-1l1npq21/logs/debug-internal.log
2021-11-10 13:43:54,565 INFO    MainThread:33598 [wandb_init.py:init():390] calling init triggers
2021-11-10 13:43:54,565 INFO    MainThread:33598 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {'batch': 16, 'epoch': 20, 'lr': 0.0001, 'seed': 21, 'save_capacity': 5, 'train_image_root': '../../train_dataset/train2014', 'train_mask_root': '../../train_dataset/train_mask', 'val_image_root': '../../train_dataset/val2014', 'val_mask_root': '../../train_dataset/val_mask', 'output_path': '../output', 'train_worker': 4, 'valid_worker': 4, 'test_worker': 4, 'wandb': True, 'wandb_project': 'alchera', 'wandb_entity': 'cv4', 'custom_name': 'test', 'TTA': True, 'test_batch': 4, 'csv_size': 256}
2021-11-10 13:43:54,565 INFO    MainThread:33598 [wandb_init.py:init():435] starting backend
2021-11-10 13:43:54,565 INFO    MainThread:33598 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-10 13:43:54,586 INFO    MainThread:33598 [backend.py:ensure_launched():198] starting backend process...
2021-11-10 13:43:54,604 INFO    MainThread:33598 [backend.py:ensure_launched():203] started backend process with pid: 33652
2021-11-10 13:43:54,627 INFO    MainThread:33598 [wandb_init.py:init():444] backend started and connected
2021-11-10 13:43:54,628 INFO    MainThread:33598 [wandb_init.py:init():503] updated telemetry
2021-11-10 13:43:54,663 INFO    MainThread:33598 [wandb_init.py:init():533] communicating current version
2021-11-10 13:43:55,556 INFO    MainThread:33598 [wandb_init.py:init():538] got version response upgrade_message: "wandb version 0.12.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-11-10 13:43:55,556 INFO    MainThread:33598 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-10 13:43:55,792 INFO    MainThread:33598 [wandb_init.py:init():576] starting run threads in backend
2021-11-10 13:43:58,626 INFO    MainThread:33598 [wandb_run.py:_console_start():1693] atexit reg
2021-11-10 13:43:58,627 INFO    MainThread:33598 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.REDIRECT
2021-11-10 13:43:58,627 INFO    MainThread:33598 [wandb_run.py:_redirect():1572] Redirecting console.
2021-11-10 13:43:58,628 INFO    MainThread:33598 [wandb_run.py:_redirect():1628] Redirects installed.
2021-11-10 13:43:58,628 INFO    MainThread:33598 [wandb_init.py:init():603] run started, returning control to user process
2021-11-10 13:43:58,629 INFO    MainThread:33598 [wandb_watch.py:watch():43] Watching
2021-11-10 13:44:03,411 INFO    MainThread:33598 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 1
2021-11-10 13:44:03,412 INFO    MainThread:33598 [wandb_run.py:_restore():1635] restore
2021-11-10 13:44:05,655 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 781
}

2021-11-10 13:44:05,976 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 781
}

2021-11-10 13:44:06,810 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 3453
}

2021-11-10 13:44:06,911 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 6436
}

2021-11-10 13:44:07,013 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 781
  total_bytes: 6436
}

2021-11-10 13:44:07,114 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6436
  total_bytes: 6436
}

2021-11-10 13:44:07,216 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6436
  total_bytes: 6436
}

2021-11-10 13:44:07,318 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6436
  total_bytes: 6436
}

2021-11-10 13:44:07,419 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6436
  total_bytes: 6436
}

2021-11-10 13:44:07,522 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6436
  total_bytes: 6436
}

2021-11-10 13:44:07,756 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6436
  total_bytes: 6436
}

2021-11-10 13:44:08,230 INFO    MainThread:33598 [wandb_run.py:_wait_for_finish():1793] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6436
  total_bytes: 6436
}
local_info {
}

2021-11-10 13:44:09,366 INFO    MainThread:33598 [wandb_run.py:_append_files():2061] logging synced files
